### PR TITLE
feat: baseline code

### PR DESCRIPTION
**Pull request by vicimilenia**
- added file structure

- added dependencies

- added base files

### CODE REVIEW

**Review by celynolivia — APPROVED** [review]

**Review by caesargusti — COMMENTED** [review]
Looks good to me

**Review by caesargusti — APPROVED** [review]

**Review by yulyulyharuka — APPROVED** [review]

**Review by ayusrina — APPROVED** [review]

**Review by polipopoliko — COMMENTED** [review]
add more baseline :)

**Review by polipopoliko — CHANGES_REQUESTED** [review]
waiting for default router

**Review by polipopoliko — APPROVED** [review]
Thank'a u a

**Pull request merged**
